apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yolo-model
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: ovms-1.x
      storage:
        key: aws-connection-minio-data-connection
        path: onnx/yolov5s-seg.onnx