apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  devMode:
    baseImage: "quay.io/hbelmiro/sonataflow-inference-pipeline-demo:dev-main-1700239050"